#!/bin/bash
set -e

if ! command -v dialog > /dev/null; then
  echo "dialog is not installed, installing..." >&2
  sudo apt-get install dialog -y
fi

# Set LINES and COLUMNS variables. (Reference: https://stackoverflow.com/a/48016366)
shopt -s checkwinsize
cat /dev/null

SELECTED=($( dialog --backtitle "Press 'space' to toggle an option, use arrow keys to go up/down, press enter to continue" --scrollbar --separate-output --checklist "Select Desktop Environment(s)" $(( ${LINES} - 5 )) $(( ${COLUMNS} - 5)) 5 \
  "1" "GNOME (Ubuntu)" OFF \
  "2" "GNOME Flashback" OFF \
  "3" "GNOME" OFF \
  "4" "KDE (Ubuntu)" OFF \
  "5" "KDE (Full)" OFF \
  "6" "KDE (Standard)" OFF \
  "7" "XFCE (Ubuntu)" OFF \
  "8" "XFCE" OFF \
  "9" "MATE (Ubuntu)" OFF \
  "10" "MATE" OFF \
  "11" "LXQt (Ubuntu)" OFF \
  "12" "LXQt" OFF \
  "13" "Budgie (Ubuntu)" OFF \
  "14" "Budgie" OFF \
  "15" "Unity" OFF \
  "16" "Cinnamon" OFF \
  "17" "Phosh core" OFF \
  "18" "UKUI" OFF \
  "19" "LXDE" OFF \
  "20" "i3" OFF \
  "21" "Sway" OFF \
  "22" "AwesomeWM" OFF \
  "23" "bspwm" OFF \
  "24" "DWM" OFF \
  "25" "Openbox" OFF \
  "26" "Enlightenment" OFF \
  3>&1 1>&2 2>&3))

for i in "${SELECTED[@]}"; do
  case $i in
    1)
      desktop+=("ubuntu-desktop")
      login_manager="gdm3"
      ;;
    2)
      desktop+=("gnome-session-flashback")
      login_manager="gdm3"
      ;;
    3)
      desktop+=("vanilla-gnome-desktop")
      login_manager="gdm3"
      ;;
    4)
      desktop+=("kubuntu-desktop")
      login_manager="sddm"
      ;;      
    5)
      desktop+=("kde-full")
      login_manager="sddm"
      ;;
    6)
      desktop+=("kde-standard")
      login_manager="sddm"
      ;;
    7)
      desktop+=("xubuntu-desktop")
      login_manager="lightdm"
      ;;
    8)
      desktop+=("xfce4" "xfce4-goodies")
      login_manager="lightdm"
      ;;
    9)
      desktop+=("ubuntu-mate-desktop")
      login_manager="lightdm"
      ;;
    10)
      desktop+=("mate-desktop")
      login_manager="lightdm"
      ;;
    11)
      desktop+=("lubuntu-desktop")
      login_manager="sddm"
      ;;
    12)
      desktop+=("lxqt")
      login_manager="sddm"
      ;;
    13)
      desktop+=("ubuntu-budgie-desktop")
      login_manager="budgie-lightdm-theme-base"
      extra_packages="budgie-extras-common budgie-extras-daemon"
      snap_package_classic="ubuntu-budgie-welcome"
      ;;
    14)
      desktop+=("budgie-desktop")
      login_manager="budgie-lightdm-theme-base"
      extra_packages="budgie-extras-common budgie-extras-daemon"
      ;; 
    15)
      desktop+=("ubuntu-unity-desktop")
      login_manager="lightdm"
      extra_packages="dbus-x11 yaru-theme-unity yaru-theme-icon yaru-theme-gtk yaru-theme-sound unity-tweak-tool atril eom vlc pluma mate-system-monitor unity-lens-music unity-lens-photos unity-lens-video"
      remove_packages="totem eog nautilus gnome-system-monitor gnome-text-editor gedit"
      ;;
    16)
      desktop+=("cinnamon")
      login_manager="lightdm"
      ;; 
    17)
      desktop+=("phose-core")
      login_manager="gdm3"
      ;;
    18)
      desktop+=("ukui-desktop-environment")
      login_manager="ukui-greeter"
      extra_packages="obconf"
      ;;
    19)
      desktop+=("lxde")
      login_manager="lxdm"
      ;;
    20)
      desktop+=("i3")
      login_manager="lightdm"
      ;; 
    21)
      desktop+=("sway")
      login_manager="sddm"
      ;; 
    22)
      desktop+=("awesome")
      login_manager="lightdm"
      ;;
    23)
      desktop+=("bspwm")
      login_manager="lightdm"
      ;;
    24)
      desktop+=("dwm")
      login_manager="lightdm"
      ;;
    25)
      desktop+=("openbox")
      login_manager="lightdm"
      extra_packages="obconf"
      ;;
    26)
      desktop+=("enlightenment")
      login_manager="lightdm"
      ;;
  esac
done

clear

echo "Updating package cache..."
sudo apt-get update

echo "Checking for package existence..."
for i in "${desktop[@]}"; do
  if [[ $(apt-cache search --names-only "^$i\$") ]]; then
    echo "$i exists..."
  else
    echo "$i does not exist, exiting..." >&2
    exit 1
  fi
done

if [[ $(apt-cache search --names-only "^$login_manager\$") ]]; then
  echo "$i exists..."
else
  echo "$i does not exist, exiting..." >&2
  exit 1
fi

echo "Installing desktop and login manager..."
sudo apt-get install -y ${desktop[@]} "${login_manager}" ${extra_packages}
if [[ ${desktop[@]} == "ubuntu-unity-desktop" ]]; then
  echo "Installing Unity 7.6"
  sudo wget https://repo.unityx.org/unityx.key
  sudo apt-key add unityx.key
  echo 'deb https://repo.unityx.org/main testing main' | sudo tee /etc/apt/sources.list.d/unity-x.list
  sudo apt-get update && sudo apt-get install -y unity
  fi
if [[ ${desktop[@]} == "ubuntu-budgie-desktop" ]]; then
  echo "Installing needed Snaps"
  sudo snap install ${snap_package_classic} --classic
fi
if [[ -n $remove_packages ]]; then
    echo "Removing unnecessary packages"
    sudo apt remove -y ${remove_packages}
    sudo apt autoremove -y
fi
if ! [[ ${desktop[@]} == "ubuntu-desktop gnome-session-flashback vanilla-gnome-desktop" ]]; then
  echo "Removing gnome-shell"
  sudo apt autoremove '^gnome-shell' --purge -y
fi
echo "Set login manager to $login_manager"
sudo dpkg-reconfigure "${login_manager}"
echo "Done!"
clear
